--- # RUNONCE PLAYBOOK EXAMPLE
- hosts: all
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Run the uptime command on all hosts and log it
      raw: /bin/uptime >> /home/ansible/uptime.logA
    - name: List the /var directory and log it
      raw: ls -al /var >> /home/ansible/dir.list
      run_once: true
