--- # Delegate to function Demo
- hosts: web
  sudo: yes
  user: ansible
  connection: ssh 
  tasks:
  - name: Run a remote ping on the application server 
    command: ping -c 4 himagiri0274 > /home/ansible/ping.out
    delegate_to: 127.0.0.1
  - name: Install a package 
    yum: pkg=lynx status=latest
