--- # My First YAML Playbook for Ansible
- hosts: web
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no 
  vars: 
    playbook_version: 0.1b
  vars_files:
    - conf/copyright.yaml
    - conf/webdefaults.yaml
  vars_prompt:
    - name:  web_domain
      prompt: web Domain
  tasks:
    - name: Install Lunx Web Browswer
      action: yum name=lynx state=installed
    - name: Check for Telnet Client
      action: yum name=telnet state=absent 
