--- # My First YAML Playbook for Ansible
- hosts: web
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no 
  vars: 
    playbook_version: 0.1b
  vars_files:
    - conf/copyright.yaml
    - conf/webdefaults.yaml
  vars_prompt:
    - name:  web_domain
      prompt: Install Packages ?
  tasks:
    - name: Install Apache web server 
      action: yum name=httpd state=installed
      notify: Restart HTTPD
    - name: Install the Lynx Web Browser
      action: yum name={{pkg_lynx}} state=installed
  handlers:
    - name: Restart HTTPD
      action: service name=httpd state=restarted
