- name: Install Apache Web Server
  yum: pkg={{ redhat_apache}} state=latest
  when: "ansible_os_family == 'RedHat' "
  ignore_errors: yes
- name: Install (Debian/Ubuntu) Apache Web Server 
  apt: pkg={{ debian_apache }} state=latest
  when: "ansible_os_family == 'Debian' "
  ignore_errors: yes
